#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SConscript2 (Python)
# 
# Purpose: Setup input files for viewNipSources.py.
# 
# Site: https://dirack.github.io
# 
# Version 1.0
# 
# Programer: Rodolfo A C Neves (Dirack) 10/03/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

from rsf.proj import *

Flow('nipsources.txt','nipsources_1','disfil col=2 format="%g " number=n')

Flow('result.txt','result','disfil col=2 format="%g " number=n')

Flow('surfsources.txt','m0s','disfil col=1 format="%g " number=n')
