#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SConscript3 (Python)
# 
# Purpose: Setup input files for viewNipSources.py.
# 
# Site: https://dirack.github.io
# 
# Version 1.0
# 
# Programer: Rodolfo A C Neves (Dirack) 10/03/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

from rsf.proj import *

txtout='testes.txt'
ascout='testes.asc'
rsffile='testes'
Flow(txtout,rsffile,'disfil col=2 format="%g " number=n')

#Flow('x.txt',txtout,'')

#Flow('y.txt',txtout,'')

