#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SConscript1 (Python)
# 
# Purpose: Setup input files for this test.
# 
# Site: https://dirack.github.io
# 
# Version 1.0
# 
# Programer: Rodolfo A C Neves (Dirack) 06/03/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

from rsf.proj import *

Flow('t0s.asc','pick.txt',
	'''
	./ascFormat.sh ${TARGETS} 1
	''')

Flow('t0s','t0s.asc','dd type=float')

Flow('m0s.asc','pick.txt',
	'''
	./ascFormat.sh ${TARGETS} 2
	''')

Flow('m0s','m0s.asc','dd type=float')

Flow('stackedSection','stackedSection.asc',
	'''
	dd type=float form=native |
	put n1=251 d1=0.008 o1=1 label1=t0 unit1=s
	n2=81 d2=0.025 o2=1.5 label2=m0 unit2=Km
	''')

Flow('parametersCube','parametersCube.asc',
	'''
	dd type=float form=native |
	put n1=8 d1=1 o1=0 label1=parameters
	n2=20331 d2=1 o2=0 label2="(t0,m0) index" n3=1 d3=1 o3=0
	''')

Flow('rnip','parametersCube',
	'''
	window n1=1 f1=1 |
	put n1=251 d1=0.008 o1=1 label1=t0 unit1=s
	n2=81 d2=0.025 o2=1.5 label2=m0 unit2=Km
	''')

Flow('rnips',['rnip','t0s','m0s'],
	'''
 	getparameter t0s=${SOURCES[1]} m0s=${SOURCES[2]} |
	put n1=26 d1=0.008 o1=1 label1=t0 unit1=s
	n2=1 d2=0.025 o2=1.5 label2=m0 unit2=Km
	''')

Flow('beta','parametersCube',
	'''
	window n1=1 f1=2 |
	put n1=251 d1=0.008 o1=1 label1=t0 unit1=s
	n2=81 d2=0.025 o2=1.5 label2=m0 unit2=Km
	''')

Flow('betas',['beta','t0s','m0s'],
	'''
 	getparameter t0s=${SOURCES[1]} m0s=${SOURCES[2]} |
	put n1=26 d1=0.008 o1=1 label1=t0 unit1=s
	n2=1 d2=0.025 o2=1.5 label2=m0 unit2=Km
	''')


